FROM golang:1.21 AS building

COPY . /building
WORKDIR /building

RUN git config --global --add safe.directory '*'

RUN make frps

FROM alpine:3

COPY --from=building /building/bin/frps /usr/bin/frps

ENTRYPOINT ["/usr/bin/frps"]
